# NumPy Array

In [27]:
import numpy as np

In [28]:
my_list = [ 1, 2, 3, 4, 5, 6, 7, 8 ]

In [29]:
type(my_list)

list

In [30]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
my_arr = np.array(my_list)

In [32]:
type(my_arr)

numpy.ndarray

In [33]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  # List inside a list

In [34]:
type(my_matrix)

list

In [35]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange()

np.arange(start,end,step) # end number wont be included


In [36]:
np.arange(0,10)  # Similar to range in Python

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.zeros((5,5))  # rows, columns is the order of the tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace()

np.linspace(start,end,num) # end is included and num - evenly spaced numbers in between start and end

In [39]:
np.linspace(0,10,2) # evenly spaced numbers will be returned

array([ 0., 10.])

In [40]:
np.linspace(0,10,11) # inorder to show all digits from 0 to 10 this is the format

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Indexing and Slicing

In [41]:
arr = np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

In [47]:
arr[0:5] = 100

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0,11)

In [50]:
slice_of_arr = arr[0:5]

In [51]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_of_arr[:]=99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Broadcasting caused the change in the original array

In [56]:
arr_copy = arr.copy()

In [57]:
arr_copy[0:5] = 100

In [58]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

The change is not affected to the original array.

In [60]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [61]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr_2d[0] # to access rows

array([1, 2, 3])

In [64]:
arr_2d[0][0] # to access a specific element

1

In [66]:
arr_2d[0,2] # alternative way to access a specific element

3

In [68]:
arr_2d[:2,1:] # to get a subset of the matrix

array([[2, 3],
       [5, 6]])

## Conditional Selection

In [69]:
arr = np.arange(1,11)

In [70]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
bool_arr = arr>4

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [76]:
# array conditional operation
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [78]:
len(dice_rolls)

29

In [79]:
total_rolls_over_two = len(dice_rolls[dice_rolls>2])

In [80]:
total_rolls_over_two

19